### ISSUE TITLE
Extract bits from SAILDART

### ISSUE THREAD

**Issue by b4** [PDP-10/waits#1]
http://saildart.org/

The simulator there does operate and run - the "filesystem" is javascript that reads files from the web archive as best I can tell.

**Comment by larsbrinkhoff** [comment]
Nice, I didn't know about the simulator.

**Comment by larsbrinkhoff** [comment]
I have now extracted all of [*,DRW].

Any particular directories you have in mind?

**Comment by b4** [comment]
The Monitor and TCP/IP directories are what i'm particularly
interested in.

On Wed, Feb 7, 2018, at 20:32, Lars Brinkhoff wrote:
> I have now extracted all of [*,DRW].


> Any particular directories you have in mind?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
Madeline Autumn-Rose
  b4@gewt.net



Links:

  1. https://github.com/PDP-10/waits/issues/1#issuecomment-363999596

**Comment by larsbrinkhoff** [comment]
Which are those?  Are they in here?  https://www.saildart.org/SYS

**Comment by larsbrinkhoff** [comment]
[NET,SYS] looks like TCP stuff.

**Comment by b4** [comment]
Yes, most of *.SYS

**Comment by larsbrinkhoff** [comment]
Ok, I'll get it to you.

**Comment by larsbrinkhoff** [comment]
Phew.  I got all of SYS, and the blobs are 15G.

**Comment by larsbrinkhoff** [comment]
It's 2G compressed.  How do you want it?  I'm out of space on my machines.

**Comment by b4** [comment]
Any file sharing method should work

**Comment by larsbrinkhoff** [comment]
Email should have been sent.

**Comment by b4** [comment]
Got it. Going through backlog of emails now.


On Mon, Feb 12, 2018, at 12:41, Lars Brinkhoff wrote:
> Email should have been sent.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
Madeline Autumn-Rose
  b4@gewt.net


Links:

  1. https://github.com/PDP-10/waits/issues/1#issuecomment-365055141

**Comment by larsbrinkhoff** [comment]
I think all public files from Saildart.org have been backed up for safe keeping.
