### ISSUE TITLE
Early hardware acquisitions

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/waits#3]
From https://apps.dtic.mil/dtic/tr/fulltext/u2/776233.pdf

| Date online | Equipment
| --- | ---
| 1966 June | PDP-6, 64K core, 8 Dectape drives, 8 Teletypes
| &nbsp;&nbsp;&nbsp; Oct. | Vidicon camera, Rancho Arm
| 1967 Nov. | Librascope Disk
| 1968 Jan. | 6 III Displays
| &nbsp;&nbsp;&nbsp; Aug. | Ampex Core (64K)
| &nbsp;&nbsp;&nbsp; Sept. | PDP-10(KA-10 processor)
| 1969 Feb. | IBM 2314 Disk
| 1970 Jun. | 3 IMLAC displays
| 1971 Mar. | Data Disc Displays (58 eventually)
| &nbsp;&nbsp;&nbsp; May | Scheinman (Stanford) Arm
| &nbsp;&nbsp;&nbsp; July? | BBN IMP
| 1972 Jan. | IBM 3330 replaces 2314
| &nbsp;&nbsp;&nbsp; April | Ampex core (128K)
| &nbsp;&nbsp;&nbsp; May | Video Switch
| 1973 Jan. | Xerox Graphics Printer

FYI @bgbaumgart

**Comment by bgbaumgart** [comment]
Lars Brinkhoff
Cc: Les and the PDP10 WAITS people
-
Thank you for actually READING this document for Hardware dates.

I even have a hardcopy paper original here on a shelf, as well as visiting with its author (Lester Earnest) IRL this past week.

https://www.saildart.org/AIM/228/pdf <https://www.saildart.org/AIM/228/pdf>

There are paper "console log books" at Lesters house three of which. I scanned into the Internet Archive a decade ago

Links to PDF and Internet Archive in mid page of this 

https://www.saildart.org/allow/pdf/index.html <https://www.saildart.org/allow/pdf/index.html> 

example LOG book at

https://archive.org/details/apr67hardwarelog00brucrich/mode/2up <https://archive.org/details/apr67hardwarelog00brucrich/mode/2up>
-

Bruce Baumgart



Les
-
Lets get those books and papers out of the closet and through my scanners - what with the "plague season holiday” we should have plenty of time to get this done this year.

AND we finally have a couple of people who actually want to read this really old stuff.
-
Bruce

> On Mar 13, 2020, at 3:54 AM, Lars Brinkhoff <notifications@github.com> wrote:
> 
> https://apps.dtic.mil/dtic/tr/fulltext/u2/776233.pdf <https://apps.dtic.mil/dtic/tr/fulltext/u2/776233.pdf>

Date online	Equipment
1966 June	PDP-6, 64K core, 8 Dectape drives, 8 Teletypes
    Oct.	Vidicon camera, Rancho Arm
1967 Nov.	Librascope Disk
1968 Jan.	6 III Displays
    Aug.	Ampex Core (64K)
    Sept.	PDP-10(KA-10 processor)
1969 Feb.	IBM 2314 Disk
1970 Jun. 3	IMLAC displays
1971 Mar.	Data Disc Displays (58 eventually)
    May	Scheinman (Stanford) Arm
    July?	BBN IMP
1972 Jan.	IBM 3330 replaces 2314
    April	Ampex core(128K)
    May	Video Switch
1973 Jan.	Xerox Graphics Printer

**Comment by larsbrinkhoff** [comment]
Adding to the above, I also see that the KL10 went into production in summer 1976.  I.e. the `FTKL` monitor switch was toggled from 0 to -1 in August.

Furthermore, the old 3330 disks were ditched in favor of RH20.  See `FTRH` appearing in October 1983.

**Comment by larsbrinkhoff** [comment]
Copied to https://github.com/PDP-10/waits/wiki/SAIL-hardware-time-line, and expanded.
