### ISSUE TITLE
Move to Saildart organization?

### ISSUE THREAD

**Issue by larsbrinkhoff** [PDP-10/waits#7]
Should this repository be moved to https://github.com/saildart?

**Comment by bgbaumgart** [comment]
Not yet - this waits repository should be general historical material relevant to all versions of WAITS as a parallel to TOPS10 and ITS under the organization PDP-10. The organization SAILDART will contain specific instances of WAITS source and binary - for example there is the Saildart/waits6.17J repository. Ask again in a month or two when we have enough good stuff to look at, so classification will be easier.

**Comment by larsbrinkhoff** [comment]
Fair enough, thanks!
